Meta-Llama-3-8B-Instruct-local:
  prompt_template: "Mixtral-8x7B-Instruct-v0.1/togetherai_prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
    model_kwargs:
      torch_dtype: 'float16'
    temperature: 0.7
    additional_terminators:
      - "<|eot_id|>"
    top_p: 1.0
    do_sample: True
  pretty_name: "Llama 3 8B Instruct local"
  link: "https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct"
